In [1]:
!pip install nltk

twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
You are using pip version 10.0.1, however version 20.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [2]:
import pandas as pd
import nltk
#nltk.download()
import numpy as np

In [10]:
dataset=pd.read_csv('Restaurant_Reviews.tsv',delimiter='\t',quoting=3)
corpus=dataset['Review'].values

In [14]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Fabienne2.Yang\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [15]:
whole_words = []
for sentence in corpus:
    tokenized_sentence = nltk.word_tokenize(sentence)
    for word in tokenized_sentence:
        whole_words.append(word)

In [16]:
whole_words = set(whole_words)
print('共有{}個單字'.format(len(whole_words)))

共有2356個單字


In [19]:
#建立字典使每一個單字有對應數值
word_index = {}
index_word = {}
n = 0
for word in whole_words:
    word_index[word] = n 
    index_word[n] = word
    n+=1

In [26]:
word_index

{'somehow': 0,
 'Salad': 1,
 'mussels': 2,
 'during': 3,
 'turn': 4,
 'man': 5,
 'Nice': 6,
 'wo': 7,
 'venturing': 8,
 'complain': 9,
 'name': 10,
 'website': 11,
 'arepas': 12,
 'thirty': 13,
 'Shrimp-': 14,
 'anyone': 15,
 'unwelcome': 16,
 'meals': 17,
 'presentation': 18,
 'IN': 19,
 '.off': 20,
 'calligraphy': 21,
 'sandwich': 22,
 'wire': 23,
 'Heimer': 24,
 'Definitely': 25,
 'problem': 26,
 'Stars': 27,
 'ambiance': 28,
 'down': 29,
 'mozzarella': 30,
 'got': 31,
 'guess': 32,
 'stale': 33,
 'buffets': 34,
 'seemed': 35,
 'alone': 36,
 'lukewarm': 37,
 'Terrible': 38,
 'above': 39,
 'Left': 40,
 'besides': 41,
 '$': 42,
 'fondue': 43,
 'authentic': 44,
 'words': 45,
 'gotten': 46,
 'pizza': 47,
 'Mediocre': 48,
 'mixed': 49,
 'place': 50,
 'liking': 51,
 'HAD': 52,
 'burgers': 53,
 'To': 54,
 'chefs': 55,
 'contained': 56,
 'frozen': 57,
 'pictures': 58,
 'refreshing': 59,
 'legs': 60,
 'corporation': 61,
 'focused': 62,
 'vain': 63,
 'ourselves': 64,
 'thick': 65,
 'life': 66

In [21]:
index_word

{0: 'somehow',
 1: 'Salad',
 2: 'mussels',
 3: 'during',
 4: 'turn',
 5: 'man',
 6: 'Nice',
 7: 'wo',
 8: 'venturing',
 9: 'complain',
 10: 'name',
 11: 'website',
 12: 'arepas',
 13: 'thirty',
 14: 'Shrimp-',
 15: 'anyone',
 16: 'unwelcome',
 17: 'meals',
 18: 'presentation',
 19: 'IN',
 20: '.off',
 21: 'calligraphy',
 22: 'sandwich',
 23: 'wire',
 24: 'Heimer',
 25: 'Definitely',
 26: 'problem',
 27: 'Stars',
 28: 'ambiance',
 29: 'down',
 30: 'mozzarella',
 31: 'got',
 32: 'guess',
 33: 'stale',
 34: 'buffets',
 35: 'seemed',
 36: 'alone',
 37: 'lukewarm',
 38: 'Terrible',
 39: 'above',
 40: 'Left',
 41: 'besides',
 42: '$',
 43: 'fondue',
 44: 'authentic',
 45: 'words',
 46: 'gotten',
 47: 'pizza',
 48: 'Mediocre',
 49: 'mixed',
 50: 'place',
 51: 'liking',
 52: 'HAD',
 53: 'burgers',
 54: 'To',
 55: 'chefs',
 56: 'contained',
 57: 'frozen',
 58: 'pictures',
 59: 'refreshing',
 60: 'legs',
 61: 'corporation',
 62: 'focused',
 63: 'vain',
 64: 'ourselves',
 65: 'thick',
 66: 'life'

In [32]:
#轉換句子為bag of words型式
def _get_bag_of_words_vector(sentence, word_index_dic, whole_words):
    sentence = sentence
    #我們先建造一個 len(whole_words)維，數值皆為 0 的向量 (ex.[0, 0, 0,......])
    vector = np.zeros(len(whole_words))
    for word in nltk.word_tokenize(sentence):
        if word in whole_words:
            #將這個評價內有出現的單詞取出，找到對應的 index，將向量中這個位置的值 +1
            vector[word_index[word]]+=1
    return vector

In [33]:
_get_bag_of_words_vector('Wow... Loved this place.', word_index, whole_words)
#array([0., 0., 0., ..., 0., 0., 0.])

array([0., 0., 0., ..., 0., 0., 0.])

In [36]:
_get_bag_of_words_vector('Crust is not good.', word_index, whole_words)

array([0., 0., 0., ..., 0., 0., 0.])